export const CHANGE_CURRENT_SONG = "CHANGE_CURRENT_SONG";
export const CHANGE_CURRENT_LYRIC = "CHANGE_CURRENT_LYRIC";
export const CHANGE_CURRENT_LYRIC_INDEX = "CHANGE_CURRENT_LYRIC_INDEX";
export const CHANGE_PLAY_LIST = "CHANGE_PLAY_LIST";
export const UNSHIFT_PLAY_LIST = "UNSHIFT_PLAY_LIST";
export const AUTO_SWITCH_CURRENT_SONG = "AUTO_SWITCH_CURRENT_SONG";
export const SWITCH_CURRENT_SONG_PREV = "SWITCH_CURRENT_SONG_PREV";
export const SWITCH_CURRENT_SONG_NEXT = "SWITCH_CURRENT_SONG_NEXT";
export const ChANGE_PLAY_MODE = "ChANGE_PLAY_MODE";
export const PLAY_MODE = {
  RANDOM: 0,
  LOOP: 1,
  ORDER: 2,
};
